import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const helveticaMono = localFont({
  src: './fonts/HelveticaMono.woff2',
  variable: '--font-helvetica-mono',
  weight: '100 900',
});

const helveticaDisplay = localFont({
  src: './fonts/HelveticaNowDisplay-Black.woff2',
  variable: '--font-helvetica-display',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaDisplay.variable} ${helveticaMono.variable} antialiased`}
      >
        <header className="bg-background z-[90001] relative text-foreground font-superbold px-2">
          <a className="block cursor-pointer">
            <div className="flex items-center justify-between text-[clamp(32px,24.5vw,143px)] leading-[.8]">
              <span>THE</span>
              <span>BLIMP</span>
            </div>
          </a>
          <div className="flex items-center font-mono text-xs uppercase">
            <div className="flex-1">
              <ul className="flex ml-2">
                {navLinks.map((l, i) => (
                  <li key={i}>
                    <a className="group relative mr-5 pl-[10px] cursor-pointer">
                      <IconThunder className="absolute top-0 -left-[5px] opacity-0 invisible group-hover:opacity-100 group-hover:visible" />
                      {l}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            <div className="flex-1 flex justify-end">
              <div>
                {' Last Updated: '}
                <time dateTime="2024-07-31">31/07/2024</time>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}

const navLinks = ['Home', 'Archive', 'Genres', 'Artists', 'Labels', 'Years', 'Locales'];

const IconThunder: React.FC<{ className?: string }> = (props) => (
  <svg
    {...props}
    width="12"
    height="10"
    viewBox="0 0 12 10"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M11 1.81398C8.79259 4.15866 6.37683 6.09794 3.59237 7.69177C2.71861 8.19191 2.50452 5.45083 2.38215 4.76667C2.31835 4.40997 2.2364 1.442 2.27575 1.48283C3.76254 3.02535 5.24069 4.60901 6.78417 6.11884C7.72216 7.03638 8.14858 8.03866 8.12738 6.3672C8.10848 4.87687 7.65503 3.55101 7.42253 2.10373C7.18418 0.620073 7.47769 5.11674 7.35603 6.61556C7.30702 7.21934 7.34336 8.26182 7.05015 8.80938C6.56065 9.72352 6.92823 6.72171 6.87726 5.67732C6.82776 4.66297 6.70128 3.65822 6.69107 2.64183C6.68923 2.45872 6.8309 0.388555 6.53148 1.17928C5.57231 3.71233 4.5426 6.24246 3.49928 8.74039C2.95503 10.0434 3.02148 6.04186 2.98061 5.56693C2.97216 5.46881 2.75455 3.24141 2.83432 3.24893C3.44798 3.30681 4.57701 4.8774 5.13507 5.26339C5.94679 5.82482 8.18486 7.56526 7.72841 6.67075C6.86246 4.97377 3.65586 3.94661 2.07627 3.20754C-0.724536 1.89709 2.71094 3.58034 3.71206 3.85603C6.08603 4.50977 8.56933 5.17909 11 5.53934"
      stroke="#EA0F32"
      strokeLinecap="round"
    ></path>
  </svg>
);
